name: sistem_peringatan_banjir_berbasis_komunitas
description: Prototipe sistem peringatan banjir berbasis komunitas untuk Kota Medan.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  flutter_local_notifications: ^17.2.4
  flutter_riverpod: ^2.5.1
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  image_picker: ^1.1.2
  supabase_flutter: ^2.6.0
  xml: ^6.5.0
  flutter_dotenv: ^6.0.1
  lucide_icons_flutter: ^3.1.14+2
  url_launcher: ^6.3.2
  image: ^4.8.0
  fl_chart: ^1.2.0
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.5
  connectivity_plus: ^7.1.1
  firebase_core: ^4.10.0
  firebase_messaging: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/app_icon.webp

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.webp"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/app_icon.png"
  android: true
  ios: true
  web: false
