// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBW1xOI8D75kG-rYpaDznyd49hTF_oRcc',
    appId: '1:331536271240:web:f01f6c1299e8db852bdc3d',
    messagingSenderId: '331536271240',
    projectId: 'sibanjir',
    authDomain: 'sibanjir.firebaseapp.com',
    storageBucket: 'sibanjir.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDv1TRDv7hUIfzeLmmbhbSGBCX1hnCh3E',
    appId: '1:331536271240:android:7023e506082fe94f2bdc3d',
    messagingSenderId: '331536271240',
    projectId: 'sibanjir',
    storageBucket: 'sibanjir.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIHSy0o2UDlB4_yY6oacTv0J4YC0O3Xh4',
    appId: '1:331536271240:ios:50b49c9e79063a7c2bdc3d',
    messagingSenderId: '331536271240',
    projectId: 'sibanjir',
    storageBucket: 'sibanjir.firebasestorage.app',
    iosBundleId: 'com.example.sistemPeringatanBanjirBerbasisKomunitas',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIHSy0o2UDlB4_yY6oacTv0J4YC0O3Xh4',
    appId: '1:331536271240:ios:50b49c9e79063a7c2bdc3d',
    messagingSenderId: '331536271240',
    projectId: 'sibanjir',
    storageBucket: 'sibanjir.firebasestorage.app',
    iosBundleId: 'com.example.sistemPeringatanBanjirBerbasisKomunitas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBW1xOI8D75kG-rYpaDznyd49hTF_oRcc',
    appId: '1:331536271240:web:db494fbbf280b13f2bdc3d',
    messagingSenderId: '331536271240',
    projectId: 'sibanjir',
    authDomain: 'sibanjir.firebaseapp.com',
    storageBucket: 'sibanjir.firebasestorage.app',
  );
}
